version: '3.3'
services:
  tyk-gateway:
    image: tykio/tyk-gateway:v3.1.2
    ports:
      - 8080:8080
    networks:
      - tyk
    volumes:
      - ./tyk.standalone.conf:/opt/tyk-gateway/tyk.conf
      - ./apps:/opt/tyk-gateway/apps
      - ./middleware:/opt/tyk-gateway/middleware
      - ./samples:/opt/tyk-gateway/samples
    environment:
      #-local swap comments below when connected to onPrem gateway
      - TYK_GW_SECRET=db471355-0424-423a-8f10-0d8f7618c479
      # On Prem version settings.
      #- TYK_GW_SECRET=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      #- HTTPS_PROXY=http://southwind.byu.edu:3128/
      #- HTTP_PROXY=http://southwind.byu.edu:3128/
    depends_on:
      - tyk-redis
  tyk-redis:
    image: redis:5.0-alpine
    networks:
      - tyk
    ports:
      - 6379:6379

networks:
  tyk: